#coding:utf-8
from django.conf.urls import patterns, include, url
from mysite.cheungssh.cheungssh import cheungssh_index
import mysite
urlpatterns = patterns('',
	url(r'^cheungssh/login/$','mysite.cheungssh.cheungssh.cheungssh_login'),
	url(r'^cheungssh/logout/$','mysite.cheungssh.cheungssh.cheungssh_logout'),
	
	url(r'^cheungssh/t/$','mysite.cheungssh.cheungssh.t1'),
	url(r'^cheungssh/sshcheck/$','mysite.cheungssh.cheungssh.sshcheck'),
	url(r'^cheungssh/excutecmd/$','mysite.cheungssh.cheungssh.excutecmd'),
	url(r'^cheungssh/cmdhistory/?$','mysite.cheungssh.cheungssh.cmdhistory'),
	url(r'^cheungssh/upload/test/$','mysite.cheungssh.cheungssh.upload_file_test'),
	url(r'^cheungssh/download/$','mysite.cheungssh.cheungssh.download_file'),
	url(r'^cheungssh/pathsearch/$','mysite.cheungssh.cheungssh.pathsearch'),
	url(r'^cheungssh/configdel/$','mysite.cheungssh.cheungssh.config_del'),
	url(r'^cheungssh/configadd/$','mysite.cheungssh.cheungssh.config_add'),
	url(r'^cheungssh/configmodify/$','mysite.cheungssh.cheungssh.config_modify'),
	url(r'^cheungssh/crontab/$','mysite.cheungssh.cheungssh.crontab'),
	url(r'^cheungssh/showcrondlog/$','mysite.cheungssh.cheungssh.showcrondlog'),
	url(r'^cheungssh/delcrondlog/$','mysite.cheungssh.cheungssh.delcrondlog'),
	url(r'^cheungssh/delkey/$','mysite.cheungssh.cheungssh.delkey'),
	url(r'^cheungssh/keyadmin/$','mysite.cheungssh.cheungssh.keyshow'),
	url(r'^cheungssh/local_upload_show/$','mysite.cheungssh.cheungssh.local_upload_show'),
	url(r'^cheungssh/$',cheungssh_index),
	url(r'^cheungssh$','mysite.cheungssh.cheungssh.cheungssh_index_redirect'),
	url(r'^cheungssh/hostinfo/$','mysite.cheungssh.hostinfo.hostinfo'),
	url(r'^cheungssh/translog/$','mysite.cheungssh.hostinfo.translog'),
	url(r'^cheungssh/groupinfo/$','mysite.cheungssh.hostinfo.groupinfo'),
	url(r'^cheungssh/groupinfoall/$','mysite.cheungssh.hostinfo.groupinfoall'),
	url(r'^cheungssh/progres/$','mysite.cheungssh.hostinfo.get_progres'),
	url(r'^cheungssh/filetrans/upload/$','mysite.cheungssh.cheungssh.filetrans_remote_upload'),
	url(r'^cheungssh/filetrans/download/$','mysite.cheungssh.cheungssh.filetrans_remote_download'),
	url(r'^cheungssh/hwinfo/$','mysite.cheungssh.cheungssh.get_hwinfo'),
	url(r'^cheungssh/showscriptcontent/$','mysite.cheungssh.cheungssh.show_scriptcontent'),
	url(r'^cheungssh/showscriptlist/$','mysite.cheungssh.cheungssh.show_scriptlist'),
	url(r'^cheungssh/showscriptdel/$','mysite.cheungssh.cheungssh.del_script'),
	url(r'^cheungssh/showscriptadd/$','mysite.cheungssh.cheungssh.add_script'),
	url(r'^cheungssh/operationrecord/$','mysite.cheungssh.cheungssh.operation_record'),
#	url(r'^cheungssh/testdownload/$',mysite.cheungssh.cheungssh.test_download.as_view()),
	url(r'^cheungssh/testdownload/$','mysite.cheungssh.cheungssh.test_download'),
	
	url(r'^cheungssh/perm$','mysite.cheungssh.cheungssh.check_permission'),
	url(r'^cheungssh/batchconfigweb/','mysite.cheungssh.cheungssh.batchconfig_web'),
	url(r'^cheungssh/addblackcmd/$','mysite.cheungssh.cheungssh.add_black_cmd'),
	url(r'^cheungssh/delblackcmd/$','mysite.cheungssh.cheungssh.del_black_cmd'),
	url(r'^cheungssh/listblackcmd/$','mysite.cheungssh.cheungssh.list_black_cmd'),
	url(r'^cheungssh/showsignrecord/$','mysite.cheungssh.cheungssh.show_sign_record'),
	url(r'^cheungssh/getalluser/$','mysite.cheungssh.cheungssh.getalluser'),
	url(r"^cheungssh/setthreshold/$","mysite.cheungssh.cheungssh.set_threshold"),
	url(r"^cheungssh/showiplimit/$","mysite.cheungssh.cheungssh.show_ip_limit"),
	url(r"^cheungssh/showipthreshold/$","mysite.cheungssh.cheungssh.show_ip_threshold"),
	url(r"^cheungssh/deliplimit/$","mysite.cheungssh.cheungssh.del_ip_limit"),
	)
